<?php

use Illuminate\Database\Seeder;

class ThingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        \App\Things::query()->insert([
            ['en_title' => 'Get wet together', 'zh_title' => '一起淋一场雨', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Ride Ferris wheel', 'zh_title' => '一起坐摩天轮', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Eat melon seeds', 'zh_title' => '一起比赛吃瓜子', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Get a dog', 'zh_title' => '一起养一条狗', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Sunrise and Sunset', 'zh_title' => '一起看日出日落', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Watch fireworks', 'zh_title' => '一起看烟花', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Make a snowman', 'zh_title' => '一起堆雪人', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Midnight movie', 'zh_title' => '一起看午夜电影', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Cook', 'zh_title' => '一起做顿饭', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Grow flowers', 'zh_title' => '一起种一种花', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Couple dress', 'zh_title' => '一起穿情侣装逛街', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Mountain climbing', 'zh_title' => '一起爬山', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Fly a kite', 'zh_title' => '一起放风筝', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Haunted House', 'zh_title' => '一起进鬼屋', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'All night', 'zh_title' => '一起通宵', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Kongming latern', 'zh_title' => '一起放孔明灯', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Kongming latern', 'zh_title' => '一起放孔明灯', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Celebrate birthday', 'zh_title' => '一起过生日', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Go to Sanya', 'zh_title' => '一起去三亚', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Watch cherry blossoms', 'zh_title' => '一起看樱花', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Champing', 'zh_title' => '一起露营', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Make a cake', 'zh_title' => '一起做蛋糕', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Make a cake', 'zh_title' => '一起做蛋糕', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'See the sea', 'zh_title' => '一起看海', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Make dumplings', 'zh_title' => '一起做饺子', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Volunteer for a day', 'zh_title' => '一起做义工', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Play billiards', 'zh_title' => '一起打台球', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Rowling', 'zh_title' => '一起划船', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Eat buffet', 'zh_title' => '一起吃自助餐', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Go to the bar', 'zh_title' => '一起去一次酒吧', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Nickname', 'zh_title' => '一起给对方起外号', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Tanabata', 'zh_title' => '一起过七夕', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Amusement Park', 'zh_title' => '一起去游乐园', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Skating', 'zh_title' => '一起去溜冰', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Go to karaoke', 'zh_title' => '一起去K歌', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Library', 'zh_title' => '一起去图书馆', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Travel', 'zh_title' => '一起去旅行', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Watch a ballgame', 'zh_title' => '一起看球赛', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Look at pandas', 'zh_title' => '一起看熊猫', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Take a photo', 'zh_title' => '一起拍一次十连拍', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Get drunk', 'zh_title' => '一起喝醉', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Release', 'zh_title' => '一起去放生', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Blessing together', 'zh_title' => '一起祈福', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Make handmade', 'zh_title' => '一起做手工品', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Bus stop kissing', 'zh_title' => '在公交车站接吻', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Bungee jumping', 'zh_title' => '一起去蹦迪', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Finish reading a book', 'zh_title' => '一起看完一本书', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Make breakfast', 'zh_title' => '一起做早餐', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Run at night', 'zh_title' => '一起夜跑', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Swimming', 'zh_title' => '一起游泳', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Riding', 'zh_title' => '一起骑行', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Go supermarket', 'zh_title' => '一起逛超时', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Go shopping', 'zh_title' => '一起去买菜', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Watch stars', 'zh_title' => '一起去天台看星星', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Roller coaster', 'zh_title' => '一起坐过山车', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Drift bottle wish', 'zh_title' => '一起放漂流瓶', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Swing', 'zh_title' => '一起放秋千', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Chorus a song', 'zh_title' => '一起合唱一首歌', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Nursing home', 'zh_title' => '一起去一次敬老院', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Go to orphanage', 'zh_title' => '一起去一次孤儿院', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Take a wedding photo', 'zh_title' => '一起拍婚纱照', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Playing poker', 'zh_title' => '一起打扑克', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Snowball fight', 'zh_title' => '一起打雪仗', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Eat ice cream', 'zh_title' => '一起吃雪糕', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Bask in the sunshine', 'zh_title' => '一起晒太阳', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Plant trees', 'zh_title' => '一起种一颗树', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Play each other', 'zh_title' => '一起扮演对方一天', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Watch horror movies', 'zh_title' => '一起在家看恐怖片', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Wake up together', 'zh_title' => '一起醒来', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Save money', 'zh_title' => '一起存钱', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Puzzle', 'zh_title' => '一起完成一幅拼图', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Live in the country', 'zh_title' => '一起在乡村住几天', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Diving', 'zh_title' => '一起潜水', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Run a marathon', 'zh_title' => '一起跑马拉松', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Go to schools', 'zh_title' => '一起逛对方的母校', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Field barbecue', 'zh_title' => '一起野外烧烤', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Morning exercises', 'zh_title' => '一起晨运', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Meet each other\' friend', 'zh_title' => '一起见对方的朋友', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Hot air balloon', 'zh_title' => '一起坐热气球', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Handstand for 30 seconds', 'zh_title' => '一起倒立30秒', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Play chess', 'zh_title' => '一起下棋', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Go fishing', 'zh_title' => '一起钓鱼', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'I love you in 8 languages', 'zh_title' => '一起学会8国语言的我爱你', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Get rid of a bad habit', 'zh_title' => '一起改掉一个坏毛病', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Go to the zoo', 'zh_title' => '一起去动物园', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Celebrate Christmas', 'zh_title' => '一起过圣诞节', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Valentine\'s day', 'zh_title' => '一起过情人节', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Spring Festival', 'zh_title' => '一起过春节', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Learn a dish', 'zh_title' => '一起学会做一道菜', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Buy a lottery ticket', 'zh_title' => '一起买一张彩票', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'A paper boat', 'zh_title' => '一起在河里放纸船', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Go for a drive', 'zh_title' => '一起兜风', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Go to Tibet', 'zh_title' => '一起去西藏', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Lego', 'zh_title' => '一起拼乐高', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Reduce weight', 'zh_title' => '一起减肥', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Take a walk', 'zh_title' => '一起散步', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Join a wedding', 'zh_title' => '一起参加朋友的婚礼', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Bury the promise', 'zh_title' => '一起在树下埋下约定', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Learn to play chess', 'zh_title' => '一起学会一种棋艺', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Attend a banquet', 'zh_title' => '一起参加一场宴会', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Wear ancient clothes', 'zh_title' => '一起穿一次古装', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Play video game', 'zh_title' => '一起打游戏', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Go to the concert', 'zh_title' => '一起去看演唱会', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],
            ['en_title' => 'Eat hotpot', 'zh_title' => '一起去吃火锅', 'created_at' => \Carbon\Carbon::now(), 'updated_at' => \Carbon\Carbon::now()],

        ]);
    }
}
